version: '3.8'

services:
  db:
    image: postgres:15-alpine
    restart: always
    environment:
      - POSTGRES_USER=kairos_admin
      - POSTGRES_PASSWORD=Malakaye1210
      - POSTGRES_DB=kairos_db
    volumes:
      - postgres_data:/var/lib/postgresql/data

  api:
    build: .
    container_name: kairos_api
    command: uvicorn app.main:app --host 0.0.0.0 --port 8000 --workers 4 --proxy-headers --forwarded-allow-ips '*'
    restart: always
    volumes:
      - .:/app
    ports:
      - "127.0.0.1:9004:8000"
    environment:
      - POSTGRES_SERVER=db
      - POSTGRES_USER=kairos_admin
      - POSTGRES_PASSWORD=Malakaye1210
      - POSTGRES_DB=kairos_db
    depends_on:
      - db

  redis:
    image: redis:7-alpine

volumes:
  postgres_data:
